name: MaximusEvents
version: 1.3
main: net.melodicalbuild.maximusevents.MaximusEvents
api-version: 1.17
authors: [ MelodicAlbuild ]
description: The Events Plugin for Maximus Server
website: https://melodicalbuild.me

commands:
  bloodmoon:
    description: The Blood Moon Event
    usage: /bloodmoon
    permission: mev.events.bloodmoon
  bossbardrop:
    description: The Bossbar Decrese System
    usage: /bossbar <bossbarid> <increment>
    permission: mev.bossbardrop
